### ISSUE TITLE
连续轰炸了4,5次，发送科科已经不管用了。

### ISSUE THREAD

**Issue by hyndaniel** [spacelan/wechat-emoticon#3]
命令行里有 “开始轰炸”
可是手机不发表情，求解决！！~~~

建议添加个日志功能

**Comment by spacelan** [comment]
恩。。有日志功能
`DEBUG=core,wechat node index.js`
设置环境变量开启日志，core是API层的日志，wechat是应用层的日志，选你想要的开

**Comment by spacelan** [comment]
估计被服务器ban了。。

**Comment by hyndaniel** [comment]
ok！下次试试日志功能！ @spacelan

---

但是我又出现一个新问题，轰炸一次之后，发送表情显示红点。
官方给出的[解释](http://kf.qq.com/faq/1211147RVfAV150428yeIj6V.html)，(/哭/哭)

**Comment by spacelan** [comment]
那我赶紧更新一下说明轰多了要被关小黑屋。。
