### ISSUE TITLE
如何抓取微信的上的表情包？

### ISSUE THREAD

**Issue by kinglisky** [spacelan/wechat-emoticon#7]
之前看教程都是网页资源表情包图片的链接，这边有没办法爬到微信的表情包，特别是自己的。

**Comment by spacelan** [comment]
https://github.com/thomasxu1991/WeChat-Emoticon 这个是不是你想要的

**Comment by kinglisky** [comment]
@spacelan 资源挺全的 O(∩_∩)O谢谢~
